indicator_symbols=[
    'SMA',
    'EMA',
    'WMA',
    'DEMA',
    'TEMA',
    'TRIMA',
    'KAMA',
    'MAMA',
    'VWAP',
    'T3',
    'MACD',
    'MACDEXT',
    'STOCH',
    'STOCHF',
    'RSI',
    'STOCHRSI',
    'WILLR',
    'ADX',
    'ADXR',
    'APO',
    'PPO',
    'MOM',
    'BOP',
    'CCI',
    'CMO',
    'ROC',
    'ROCR',
    'AROON',
    'AROONOSC',
    'MFI',
    'TRIX',
    'ULIOSC',
    'DX',
    'MINUS_DI',
    'PLUS_DI',
    'MINUS_DM',
    'PLUS_DM',
    'BBANDS',
    'MIDPOINT',
    'MIDPRICE',
    'SAR',
    'TRANGE',
    'ATR',
    'NATR',
    'AD',
    'ADOSC',
    'OBV',
    'HT_TRENDLINE',
    'HT_SINE',
    'HT_TRENDMODE',
    'HT_DCPERIOD',
    'HT_DCPHASE',
    'HT_PHASOR'
]

indicator_description=[
    'This API returns the simple moving average (SMA) values.',
    'This API returns the exponential moving average (EMA) values.',
    'This API returns the weighted moving average (WMA) values.',
    'This API returns the double exponential moving average (DEMA) values.',
    'This API returns the triple exponential moving average (TEMA) values.',
    'This API returns the triangular moving average (TRIMA) values.',
    'This API returns the Kaufman adaptive moving average (KAMA) values.',
    'This API returns the MESA adaptive moving average (MAMA) values.',
    'This API returns the volume weighted average price (VWAP) for intraday time series.',
    'This API returns the triple exponential moving average (T3) values.',
    'This API returns the moving average convergence / divergence (MACD) values.',
    'This API returns the moving average convergence / divergence values with controllable moving average type.',
    'This API returns the stochastic oscillator (STOCH) values.',
    'This API returns the stochastic fast (STOCHF) values.',
    'This API returns the relative strength index (RSI) values.',
    'This API returns the stochastic relative strength index (STOCHRSI) values.',
    "This API returns the Williams' %R (WILLR) values.",
    'This API returns the average directional movement index (ADX) values.',
    'This API returns the average directional movement index rating (ADXR) values.',
    'This API returns the absolute price oscillator (APO) values.',
    'This API returns the percentage price oscillator (PPO) values.',
    'This API returns the momentum (MOM) values.',
    'This API returns the balance of power (BOP) values.',
    'This API returns the commodity channel index (CCI) values.',
    'This API returns the Chande momentum oscillator (CMO) values.',
    'This API returns the rate of change (ROC) values.',
    'This API returns the rate of change ratio (ROCR) values.',
    'This API returns the Aroon (AROON) values.',
    'This API returns the Aroon oscillator (AROONOSC) values.',
    'This API returns the money flow index (MFI) values.',
    'This API returns the 1-day rate of change of a triple smooth exponential moving average (TRIX) values.',
    'This API returns the ultimate oscillator (ULTOSC) values.',
    'This API returns the directional movement index (DX) values.',
    'This API returns the minus directional indicator (MINUS_DI) values.',
    'This API returns the plus directional indicator (PLUS_DI) values.',
    'This API returns the minus directional movement (MINUS_DM) values.',
    'This API returns the plus directional movement (PLUS_DM) values.',
    'This API returns the Bollinger bands (BBANDS) values.',
    'This API returns the midpoint (MIDPOINT) values. MIDPOINT = (highest value + lowest value)/2.',
    'This API returns the midpoint price (MIDPRICE) values. MIDPRICE = (highest high + lowest low)/2.',
    'This API returns the parabolic SAR (SAR) values.',
    'This API returns the true range (TRANGE) values.',
    'This API returns the average true range (ATR) values.',
    'This API returns the normalized average true range (NATR) values.',
    'This API returns the Chaikin A/D line (AD) values.',
    'This API returns the Chaikin A/D oscillator (ADOSC) values.',
    'This API returns the on balance volume (OBV) values.',
    'This API returns the Hilbert transform, instantaneous trendline (HT_TRENDLINE) values.',
    'This API returns the Hilbert transform, sine wave (HT_SINE) values.',
    'This API returns the Hilbert transform, trend vs cycle mode (HT_TRENDMODE) values.',
    'This API returns the Hilbert transform, dominant cycle period (HT_DCPERIOD) values.',
    'This API returns the Hilbert transform, dominant cycle phase (HT_DCPHASE) values.',
    'This API returns the Hilbert transform, phasor components (HT_PHASOR) values.',
]